# Generated by Django 2.1.8 on 2020-01-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '用户拓展信息', 'verbose_name_plural': '用户拓展信息'},
        ),
    ]
